#pragma once
#define ERROR 0xFF
#define BOARD_STATE_CHANGED 0xAA
#define PING_REQUEST 0xA0
#define PING_RESPONSE 0xA1
#define SEND_LOG 0xA8
#define SET_LEDS_STATE_REQUEST 0xA4
#define SET_LEDS_STATE_RESPONSE 0xA5