#pragma once
#define ERROR 0xFF
#define PING_REQUEST 0xA0
#define PING_RESPONSE 0xA1
#define GET_BOARD_STATE_REQUEST  0xA2
#define GET_BOARD_STATE_RESPONSE 0xA3
#define SET_LEDS_STATE_REQUEST 0xA4
#define SET_LEDS_STATE_RESPONSE 0xA5
#define GET_LAST_MODIFED_SQUARE_REQUEST 0xA6
#define GET_LAST_MODIFED_SQUARE_RESPONSE 0xA7