PING_REQUEST = 0xA0
PING_RESPONSE = 0xA1
GET_BOARD_STATE_REQUEST = 0xA2
GET_BOARD_STATE_RESPONSE = 0xA3
SET_LEDS_STATE_REQUEST = 0xA4
SET_LEDS_STATE_RESPONSE = 0xA5
GET_LAST_MODIFED_SQUARE_REQUEST = 0xA6
GET_LAST_MODIFED_SQUARE_RESPONSE = 0xA7

